name: pvlib
dependencies:
    - python=2.7
    - numpy
    - scipy
    - pandas
    - pytz
    - ephem
    - numba
    - ipython
    - jupyter
    - sphinx
    - numpydoc
    - matplotlib
    - seaborn